const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getCards: () => ipcRenderer.invoke('cards:get'),
  refreshCards: () => ipcRenderer.invoke('cards:refresh'),
  getCollection: () => ipcRenderer.invoke('collection:get'),
  setCollection: (cardId, bucket, value) => ipcRenderer.invoke('collection:set', cardId, bucket, value),
  openCollectionView: () => ipcRenderer.invoke('collection-view:open'),
  backupCollection: () => ipcRenderer.invoke('collection:backup'),
  listBackups: () => ipcRenderer.invoke('collection:listBackups'),
  restoreBackup: (filename) => ipcRenderer.invoke('collection:restoreBackup', filename),
  renameBackup: (filename, label) => ipcRenderer.invoke('collection:renameBackup', filename, label),
  setBackupLocked: (filename, locked) => ipcRenderer.invoke('collection:setBackupLocked', filename, locked),
  overwriteBackup: (filename) => ipcRenderer.invoke('collection:overwriteBackup', filename),
  windowMinimize: () => ipcRenderer.invoke('window:minimize'),
  windowToggleMaximize: () => ipcRenderer.invoke('window:toggle-maximize'),
  windowClose: () => ipcRenderer.invoke('window:close'),
  publishSite: () => ipcRenderer.invoke('publish:run'),
  openDeckBuilder: () => ipcRenderer.invoke('deck-builder:open'),
  getDecks: () => ipcRenderer.invoke('decks:get'),
  saveDeck: (deck) => ipcRenderer.invoke('decks:save', deck),
  deleteDeck: (deckId) => ipcRenderer.invoke('decks:delete', deckId),
  openExternalLink: (url) => ipcRenderer.invoke('shell:openExternal', url),
  getDeckPublishState: () => ipcRenderer.invoke('decks:getPublishState'),
  publishDecks: (deckIds) => ipcRenderer.invoke('decks:publish', deckIds),
  getAltCardNames: () => ipcRenderer.invoke('cards:altNames'),
  openTrading: () => ipcRenderer.invoke('trading:open'),
  getLookingList: () => ipcRenderer.invoke('looking:get'),
  reorderLooking: (ids) => ipcRenderer.invoke('looking:reorder', ids),
  reorderTrade: (ids) => ipcRenderer.invoke('trade:reorder', ids),
  setLookingMany: (updates) => ipcRenderer.invoke('looking:setMany', updates),
  getTradeList: () => ipcRenderer.invoke('trade:get'),
  setTradeQty: (printingId, qty) => ipcRenderer.invoke('trade:set', printingId, qty),
  setTradeQtys: (updates) => ipcRenderer.invoke('trade:setMany', updates),
  getPrices: () => ipcRenderer.invoke('prices:get'),
  refreshPrices: () => ipcRenderer.invoke('prices:refresh'),
  setPriceOverride: (printingId, idProduct) => ipcRenderer.invoke('prices:setOverride', printingId, idProduct)
});
